added check for ini file existance

diff --git a/bash-ini-parser b/bash-ini-parser
--- a/bash-ini-parser
+++ b/bash-ini-parser
@@ -7,6 +7,11 @@ function readini()
 	eval "${PREFIX}LAST_SECTION=\"default\""
 	eval "${PREFIX}SECTIONS="
 
+	if [ ! -e $INI_FILE ]; then
+		echo "Error: ${INI_FILE} does not exist."
+		exit 1
+	fi
+
 	while read -r line || [ -n "$line" ]; do
 		#skip blank lines
 		if [ -z "$line" ]; then
@@ -47,7 +52,8 @@ function get_keys()
 	fi
 	keys=
 	section=$1
-	if [ -z $1 ]; then
+	echo $section
+	if [ -z "$1" ]; then
 		section="default"	
 	fi
 	sectionName=`echo $section | xargs`
